### ISSUE TITLE
Only 6970 train questions in data/dictionaries/train_subgraph.json

### ISSUE THREAD

**Issue by apoorvumang** [zhenjia2017/EXAQT#2]
I just noticed that data/dictionaries/train_subgraph.json contains only 6970 questions rather than 9708 as mentioned in the paper. Test and dev_subgraph contain the correct number of questions. However data/TimeQuestions/train.json does contain all 9708 questions.

Where can I obtain the answer graphs for the remaining train questions?

Thanks

**Comment by zhenjia2017** [comment]
The questions without ground truth in the subgraph were removed. In the code get_relational_graph.py, line 421-422, if do not use "if data['id'] in good_questions or data['id'] in ok_questions:", the subgraphs of all the questions in the training set will be generated.

**Comment by apoorvumang** [comment]
Got it, thanks!
