### ISSUE TITLE
Regarding the actual evaluations on EXAQT

### ISSUE THREAD

**Issue by theartpiece** [zhenjia2017/EXAQT#3]
Will it be possible to provide the evaluations of EXAQT on the train/test data?

**Comment by zhenjia2017** [comment]
Thank you for your interest! I upload the evaluations of EXAQT on the train and test data to the github, under the folder of "result". "gcn_result_train_exaqt.txt" is for train data and "gcn_result_test_exaqt.txt" is for test data. The format of the file is:
question_no|P@1|Hit@5|MRR|top-1 answer_id#score;top-2 answer_id#score;top-3 answer_id#score;top-4 answer_id#score;top-5 answer_id#score
