### ISSUE TITLE
Background KG

### ISSUE THREAD

**Issue by SRL94** [zhenjia2017/EXAQT#7]
Hi,

Could you please share the background KG? It looks like you had a train_subgraph.json. Thanks a lot!

Best regards
Sirui

**Comment by zhenjia2017** [comment]
Hi,
Thanks a lot for your interest in our project!
Please download the training, dev, and test graph data from [here](https://qa.mpi-inf.mpg.de/exaqt/gcn_data.zip). These data are for training and testing gcn model in the answer prediction stage. If you need other files, please let me know. If there is any issue with the code when you reproduce the results, please let me know. 

Best Regards,
Zhen

**Comment by SRL94** [comment]
Thanks a lot!
